export const webprojects = [
    {
        "id": 1124,
        "title": "Dad-Joke-Maker",
        "description": "Random Generated Dad Joke",
        "lead": "TT",
        "type": "front-end",
        "status": "not-started",
        "proguess": 10,
        "priority": 0,
        "favorite": "✔️",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "Hex-Color-Picker",
        "description": "Chooses a Random Color for You!",
        "lead": "Mike T",
        "type": "full-stack",
        "status": "not-started",
        "proguess": 20,
        "priority": 0,
        "favorite": "❌",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "A-Spelling-Bee-Game",
        "description": "Generate Words to Spell!",
        "lead": "Mike T",
        "type": "Static",
        "status": "not-started",
        "proguess": 50,
        "priority": 1,
        "favorite": "✔️",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "Hangman",
        "description": "It's a Digital Alarm That Wakes You UP!",
        "lead": "Andy T",
        "type": "full-stack",
        "status": "not-started",
        "proguess": 75,
        "priority": 1,
        "favorite": "❌",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "Rock-Paper-Scissors",
        "description": "It's a Digital Alarm That Wakes You UP!",
        "lead": "Billy T",
        "type": "front-end",
        "status": "not-started",
        "proguess": 90,
        "priority": 1,
        "favorite": "✔️",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "Baking-Guide",
        "description": "It's a Digital Alarm That Wakes You UP!",
        "lead": "JT",
        "type": "full-stack",
        "status": "not-started",
        "proguess": 80,
        "priority": 1,
        "favorite": "✔️",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "Being-Not-Broke-Simulator",
        "description": "It's a Digital Alarm That Wakes You UP!",
        "lead": "Mike T",
        "type": "static",
        "status": "not-started",
        "proguess": 10,
        "priority": 1,
        "favorite": "✔️",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    },
    {
        "id": 1234,
        "title": "RPG-Game",
        "description": "It's a Digital Alarm That Wakes You UP!",
        "lead": "MT",
        "type": "front-end",
        "status": "not-started",
        "proguess": 1,
        "priority": 1,
        "favorite": "❌",
        "beginDate": Date(2019, 10, 1),
        "endDate": Date(2020, 10, 1)
    }
]